# ===================================================================
# PASSWORD ENCRYPTION CONFIGURATION
# ===================================================================

password:
  encryption:
    secret: ${PASSWORD_ENCRYPTION_SECRET:YourStrongSecretKeyHere}
    salt: ${PASSWORD_ENCRYPTION_SALT:YourStrongSaltValueHere}
