spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://localhost:27018/authen-hub
      auto-index-creation: true
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  rsocket:
    server:
      mapping-path: /rsocket
      transport: websocket
      port: 7000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 212sd1f231s4d32f1a5s64d56asdasd
            client-secret: 3902480293kmnsdmlksdjfkldsjnklfjmsadc234555
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          facebook:
            client-id: 212sd1f231s4d32f1a5s64d56asdasd
            client-secret: 3902480293kmnsdmlksdjfkldsjnklfjmsadc234555
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - public_profile
              - email
            user-info-uri: https://graph.facebook.com/me
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8118
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.springframework.rsocket: DEBUG
    com.mangahub: DEBUG
    org.springframework.security: DEBUG

cors:
  allowed-origins: http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  exposed-headers: "*"
  allow-credentials: true
  max-age: 3600

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 604800000 # 7 days

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

# Admin account default
admin:
  username: admin
  email: admin@mangahub.com
  password: Admin@123
  fullName: Administrator