# ===================================================================
# SWAGGER CONFIGURATION
# ===================================================================

# SpringDoc OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
    display-request-duration: true
  show-actuator: false
  packages-to-scan: com.authenhub.controller
  paths-to-match: /api/**
