# ===================================================================
# MAIN CONFIGURATION FILE
# ===================================================================

spring:
  profiles:
    # Set the active profile
    active: dev
    # Include other configuration files
    include:
#      - kafka
      - database
      - mail
      - payment
      - social
      - server
      - ai
      - logging

  # Application settings
  main:
    allow-bean-definition-overriding: true

  # File upload settings
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB

  # JSON settings
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh
